services:
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/app"
      OLLAMA_URL: "http://host.docker.internal:11434"
    ports:
      - "80:80"
    volumes:
      - .:/app
      - api_db:/data


  scraper:
    build:
      context: .
      dockerfile: docker/scrape_characters.Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/app"
      OLLAMA_URL: "http://host.docker.internal:11434"
    profiles: ["scrape"]
    volumes:
      - .:/app
      - api_db:/data

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

volumes:
  api_db:
  pg_data:
