from pydantic import BaseModel


class CharacterSpecialAbilityModel(BaseModel):
    name: str
    description: str
    target: str
    range: int
    area_of_effect: int
    health_add: int
    defense_add: int
    movement_add: int
    attack_power_add: int
    will_stun: bool
    cost: int # Generated by adding health_add, defense_add, movement_add, attack_power_add. Will stun doubles the cost.