from enum import Enum

from pydantic import BaseModel

character_power_scale_data = [
    {'tier': 1, 'label': 'tier_11', 'name': 'Infinitesimal'},
    {'tier': 1.1, 'label': 'tier_11-c', 'name': 'Low Hypoverse level'},
    {'tier': 1.2, 'label': 'tier_11-b', 'name': 'Hypoverse level'},
    {'tier': 1.3, 'label': 'tier_11-a', 'name': 'High Hypoverse level'},
    {'tier': 2, 'label': 'tier_10', 'name': 'Human'},
    {'tier': 2.1, 'label': 'tier_10-c', 'name': 'Below Average Human level'},
    {'tier': 2.2, 'label': 'tier_10-b', 'name': 'Human level'},
    {'tier': 2.3, 'label': 'tier_10-a', 'name': 'Athlete level'},
    {'tier': 3, 'label': 'tier_9', 'name': 'Superhuman'},
    {'tier': 3.1, 'label': 'tier_9-c', 'name': 'Street level'},
    {'tier': 3.2, 'label': 'tier_9-b', 'name': 'Wall level'},
    {'tier': 3.3, 'label': 'tier_9-a', 'name': 'Small Building level'},
    {'tier': 4, 'label': 'tier_8', 'name': 'Urban'},
    {'tier': 4.1, 'label': 'tier_8-c', 'name': 'Building level'},
    {'tier': 4.2, 'label': 'tier_high_8-c', 'name': 'Large Building level'},
    {'tier': 4.3, 'label': 'tier_8-b', 'name': 'City Block level'},
    {'tier': 4.4, 'label': 'tier_8-a', 'name': 'Multi-City Block level'},
    {'tier': 5, 'label': 'tier_7', 'name': 'Nuclear'},
    {'tier': 5.1, 'label': 'tier_low_7-c', 'name': 'Small Town level'},
    {'tier': 5.2, 'label': 'tier_7-c', 'name': 'Town level'},
    {'tier': 5.3, 'label': 'tier_high_7-c', 'name': 'Large Town level'},
    {'tier': 5.4, 'label': 'tier_low_7-b', 'name': 'Small City level'},
    {'tier': 5.5, 'label': 'tier_7-b', 'name': 'City level'},
    {'tier': 5.6, 'label': 'tier_7-a', 'name': 'Mountain level'},
    {'tier': 5.7, 'label': 'tier_high_7-a', 'name': 'Large Mountain level'},
    {'tier': 6, 'label': 'tier_6', 'name': 'Tectonic'},
    {'tier': 6.1, 'label': 'tier_6-c', 'name': 'Island level'},
    {'tier': 6.2, 'label': 'tier_high_6-c', 'name': 'Large Island level'},
    {'tier': 6.3, 'label': 'tier_low_6-b', 'name': 'Small Country level'},
    {'tier': 6.4, 'label': 'tier_6-b', 'name': 'Country level'},
    {'tier': 6.5, 'label': 'tier_high_6-b', 'name': 'Large Country level'},
    {'tier': 6.6, 'label': 'tier_6-a', 'name': 'Continent level'},
    {'tier': 6.7, 'label': 'tier_high_6-a', 'name': 'Multi-Continent level'},
    {'tier': 7, 'label': 'tier_5', 'name': 'Substellar'},
    {'tier': 7.1, 'label': 'tier_5-c', 'name': 'Moon level'},
    {'tier': 7.2, 'label': 'tier_low_5-b', 'name': 'Small Planet level'},
    {'tier': 7.3, 'label': 'tier_5-b', 'name': 'Planet level'},
    {'tier': 7.4, 'label': 'tier_5-a', 'name': 'Large Planet level'},
    {'tier': 7.5, 'label': 'tier_high_5-a', 'name': 'Brown Dwarf level'},
    {'tier': 8, 'label': 'tier_4', 'name': 'Stellar'},
    {'tier': 8.1, 'label': 'tier_low_4-c', 'name': 'Small Star level'},
    {'tier': 8.2, 'label': 'tier_4-c', 'name': 'Star level'},
    {'tier': 8.3, 'label': 'tier_high_4-c', 'name': 'Large Star level'},
    {'tier': 8.4, 'label': 'tier_4-b', 'name': 'Solar System level'},
    {'tier': 8.5, 'label': 'tier_4-a', 'name': 'Multi-Solar System level'},
    {'tier': 9, 'label': 'tier_3', 'name': 'Cosmic'},
    {'tier': 9.1, 'label': 'tier_3-c', 'name': 'Galaxy level'},
    {'tier': 9.2, 'label': 'tier_3-b', 'name': 'Multi-Galaxy level'},
    {'tier': 9.3, 'label': 'tier_3-a', 'name': 'Universe level'},
    {'tier': 9.4, 'label': 'tier_high_3-a', 'name': 'High Universe level'},
    {'tier': 10, 'label': 'tier_2', 'name': 'Multiversal'},
    {'tier': 10.1, 'label': 'tier_low_2-c', 'name': 'Universe level+'},
    {'tier': 10.2, 'label': 'tier_2-c', 'name': 'Low Multiverse level'},
    {'tier': 10.3, 'label': 'tier_2-b', 'name': 'Multiverse level'},
    {'tier': 10.4, 'label': 'tier_2-a', 'name': 'Multiverse level+'},
    {'tier': 11, 'label': 'tier_1', 'name': 'Higher Infinity'},
    {'tier': 11.1, 'label': 'tier_low_1-c', 'name': 'Low Complex Multiverse level'},
    {'tier': 11.2, 'label': 'tier_1-c', 'name': 'Complex Multiverse level'},
    {'tier': 11.3, 'label': 'tier_high_1-c', 'name': 'High Complex Multiverse level'},
    {'tier': 11.4, 'label': 'tier_1-b', 'name': 'Hyperverse level'},
    {'tier': 11.5, 'label': 'tier_high_1-b', 'name': 'High Hyperverse level'},
    {'tier': 11.6, 'label': 'tier_low_1-a', 'name': 'Low Outerverse level'},
    {'tier': 11.7, 'label': 'tier_1-a', 'name': 'Outerverse level'},
    {'tier': 11.8, 'label': 'tier_high_1-a', 'name': 'High Outerverse level'},
    {'tier': 12, 'label': 'tier_0', 'name': 'Boundless'}
]

class CharacterPowerScaleModel(BaseModel):
    powerscale_id: int | None = None
    tier: float
    label: str
    name: str