from src.model.character_special_ability_model import CharacterSpecialAbilityModel
from src.model.ollama_character_model import OllamaSpecialAbilityModel


class BuildCharacterSpecialAbilityFromGeneratedProcess:
    def __init__(self):
        pass

    def execute(self, generated_abilities: list[OllamaSpecialAbilityModel]):
        constructed = []

        for model in generated_abilities:
            stun_mult = 2 if model.will_stun else 1
            cost = (abs(model.health_add) +
                    abs(model.defense_add) +
                    abs(model.movement_add) +
                    abs(model.attack_power_add)
                    ) * stun_mult
            constructed.append(CharacterSpecialAbilityModel(
                name=model.name,
                description=model.description,
                target=model.target.value,
                range=model.range,
                area_of_effect=model.area_of_effect,
                health_add=model.health_add,
                defense_add=model.defense_add,
                movement_add=model.movement_add,
                attack_power_add=model.attack_power_add,
                will_stun=model.will_stun,
                cost=cost
                # Generated by adding health_add, defense_add, movement_add, attack_power_add. Will stun doubles the cost.
            ))

        return constructed
