from src.model.character_special_ability_model import CharacterSpecialAbilityModel
from src.model.ollama_character_model import OllamaSpecialAbilityModel, AbilityTypeModel


class BuildCharacterSpecialAbilityFromGeneratedProcess:
    def __init__(self):
        pass

    def execute(self, generated_abilities: list[OllamaSpecialAbilityModel]):
        constructed = []

        for model in generated_abilities:
            ## Cannot stun if a buff
            if model.type is AbilityTypeModel.BUFF:
                model.will_stun = False

            stun_mult = 2 if model.will_stun else 1
            cost = (abs(model.health_impact_factor) +
                    abs(model.defense_impact_factor) +
                    abs(model.movement_impact_factor) +
                    abs(model.attack_power_impact_factor)
                    ) * stun_mult

            effect_factor = 1 if model.type is AbilityTypeModel.BUFF else -1

            constructed.append(CharacterSpecialAbilityModel(
                name=model.name,
                description=model.description,
                target=model.target.value,
                range=model.range,
                area_of_effect=model.area_of_effect,
                health_add=model.health_impact_factor * effect_factor,
                defense_add=model.defense_impact_factor * effect_factor,
                movement_add=model.movement_impact_factor * effect_factor,
                attack_power_add=model.attack_power_impact_factor * effect_factor,
                will_stun=model.will_stun,
                cost=cost
                # Generated by adding health_add, defense_add, movement_add, attack_power_add. Will stun doubles the cost.
            ))

        return constructed
